project_id = "searce-msp-gcp"
secret_id = "secret_hai"
secret_data = "kyuBtau"
topic_name = "testtopic"
subscription_name = "testsubscription"
push_url = "https://fairtricks.com"
service_account_email = "138101788-compute@developer.gserviceaccount.com"
